version: '3.6'
services:
  db:
    image: postgis/postgis:14-3.3
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: password
    networks:
      - app_net
    command: postgres -N 500
    ports:
      - 5432:5432
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - type: tmpfs
        target: /var/lib/postgresql/data

  redis-cluster:
    image: channguyen/redis-cluster:latest
    restart: always
    networks:
      - app_net
    ports:
      - 30001:30001
      - 30002:30002
      - 30003:30003
      - 30004:30004
      - 30005:30005
      - 30006:30006

networks:
  app_net:
    name: app
