app:
  environment: 'development'
  title: 'development'
  description: 'development'
  host: '127.0.0.1' # uses for web server only
  port: 8080 # uses for web server only
  root_path: ${ROOT_PATH:``}
  workers: ${WORKERS:0}

databases:
  url: ${DB_URL:localhost}
  replicaEnabled: ${DB_REPLICA_ENABLED:false}
  replicaUrl: ${DB_REPLICA_URL:localhost}
  name: ${DB_NAME:local}
  username: ${DB_USERNAME:local}
  password: ${DB_PASSWORD:local}
  prepareThreshold: 0
  replicaTimeoutSeconds: 10
  primaryTimeoutSeconds: 5
  portNumber: ${DB_PORT:5432}

aws:
  accessKeyId: ${AWS_KEY_ID:'temp'}
  secretAccessKey: ${AWS_SECRET_KEY:'temp'}
  region: ${AWS_REGION:us-east-1}

sqs:
  url: ${SQS_URL:`http://localhost:4566`}
  generalQueueUrl: ${GENERAL_SQS_QUEUE_URL:`http://localhost:4566/000000000000/general`}

s3:
  url: ${S3_URL:`http://localhost:4566`}
  publicBucketName: ${PUBLIC_S3_BUCKET:public}
  privateBucketName: ${PRIVATE_S3_BUCKET:private}

redis:
  hosts: ${REDIS_HOSTS:}
  user: ${REDIS_USER:}
  password: ${REDIS_PASSWORD:}
  ssl: ${REDIS_SSL:false}
  timeout: ${REDIS_TIMEOUT:1000}
  port: ${REDIS_PORT:6379}